### ISSUE TITLE
Extra trailing space character in action command output when running any action

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#19]
When an action runs any command, the output has an extra space within the single quotes that shouldn't be there.

### Actual behaviour 

`Running 'command ' from ops.yml...`

### Expected behaviour

`Running 'command' from ops.yml...`

### Relevant part of code

https://github.com/nickthecook/ops/blob/95d43fc41c89e794086bdbe957fc9e05933e718c/lib/ops.rb#L56

### Possible cause

Whatever `#{action}` returns probably has an extra space.

**Comment by nickthecook** [comment]
Fixed in 0.8.10.
