### ISSUE TITLE
Feature: `skip_in_envs`

### ISSUE THREAD

**Issue by rcgtnick** [nickthecook/ops#65]
We have some actions that should only be run in certain environments, and we're using `in_envs` or `not_in_envs` for those.

That works when we want to throw an error when those get run in the wrong environment, e.g. to inform a user that it's not allowed. However, there are actions we want to _skip_ in some environments, but not consider it an error, e.g. starting local services so we can run e2e tests (should happen in `ci` and `dev`, but not in `staging` or `production`).

We can implement logic such as `[ "$environment" == "dev" ] && ...`, but that is cumbersome, especially when testing for multiple environments.

**Comment by nickthecook** [comment]
Fixed in 1.8.0.
