### ISSUE TITLE
Apk dependencies don't always get installed

### ISSUE THREAD

**Issue by Lost-in-Space** [nickthecook/ops#66]
Apk dependencies met check can match the wrong dependency causing some apk dependencies to not be installed

**Comment by rcgtnick** [comment]
Fixed in 1.11.1.

`apk` dependency was not pinning its regex with `^` and `$`. Now it is.

**Comment by nickthecook** [comment]
Fixed in 1.11.1.

`apk` dependency wasn't pinning its regex with `^` and `$`. Now it is.
