### ISSUE TITLE
gemspec: Increase 'required_ruby_version' to 2.6

### ISSUE THREAD

**Issue by ErikHumphrey** [nickthecook/ops#76]
Version 1.20.3 bumped the version of the `net-ssh` dependency to v7, but `net-ssh` was changed to require Ruby 2.6 in this major version. As such, `ops_team` can no longer be installed on Ruby 2.5.

You could also consider using `[Gem::Requirement.new()](https://docs.ruby-lang.org/en/3.0/Gem/Requirement.html)` here, though I'm not sure if that would have any benefit.

**Comment by nickthecook** [comment]
Thanks! Fixed in 1.21.1.

I've yanked the two affected gem releases: 1.20.3 and 1.21.0.
